# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = ""
name = "WT loyalty points"
handle = "wt-loyalty-points"
application_url = "https://briefly-grip-trim-donated.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sohel-test-webiators.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_fulfillments,read_orders,read_price_rules,read_products,read_content"

[auth]
redirect_urls = [
  "https://briefly-grip-trim-donated.trycloudflare.com/auth/callback",
  "https://briefly-grip-trim-donated.trycloudflare.com/auth/shopify/callback",
  "https://briefly-grip-trim-donated.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
